%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.21.7

-ifndef(kv_pb).
-define(kv_pb, true).

-define(kv_pb_gpb_version, "4.21.7").


-ifndef('DATA_PB_H').
-define('DATA_PB_H', true).
-record(data,
        {key                    :: unicode:chardata() | undefined, % = 1, required
         value                  :: unicode:chardata() | undefined % = 2, required
        }).
-endif.

-ifndef('SET_REQUEST_PB_H').
-define('SET_REQUEST_PB_H', true).
-record(set_request,
        {payload                :: kv_pb:data() | undefined % = 1, required
        }).
-endif.

-ifndef('SET_RESPONSE_PB_H').
-define('SET_RESPONSE_PB_H', true).
-record(set_response,
        {result                 :: ok | internal | integer() | undefined % = 1, required, enum set_response.error
        }).
-endif.

-ifndef('GET_REQUEST_PB_H').
-define('GET_REQUEST_PB_H', true).
-record(get_request,
        {key                    :: unicode:chardata() | undefined % = 1, required
        }).
-endif.

-ifndef('GET_RESPONSE_PB_H').
-define('GET_RESPONSE_PB_H', true).
-record(get_response,
        {result                 :: ok | not_found | internal | integer() | undefined, % = 1, required, enum get_response.error
         payload                :: kv_pb:data() | undefined % = 2, optional
        }).
-endif.

-ifndef('REQ_ENVELOPE_PB_H').
-define('REQ_ENVELOPE_PB_H', true).
-record(req_envelope,
        {type                   :: 'SET_REQ' | 'SET_RESP' | 'GET_REQ' | 'GET_RESP' | integer() | undefined, % = 1, required, enum req_envelope.msg_type
         set_req                :: kv_pb:set_request() | undefined, % = 2, optional
         set_resp               :: kv_pb:set_response() | undefined, % = 3, optional
         get_req                :: kv_pb:get_request() | undefined, % = 4, optional
         get_resp               :: kv_pb:get_response() | undefined % = 5, optional
        }).
-endif.

-endif.
